#!/bin/bash
# Скрипт для проверки датчиков в Home Assistant

echo "=== Поиск всех датчиков waveshare ==="
echo ""
echo "Датчики температуры:"
ha core states list | grep "waveshare.*temperature" || echo "Датчики температуры не найдены"
echo ""
echo "Датчики влажности:"
ha core states list | grep "waveshare.*humidity" || echo "Датчики влажности не найдены"
echo ""
echo "Все датчики waveshare:"
ha core states list | grep "waveshare.*sensor" || echo "Датчики не найдены"
echo ""
echo "=== Проверка конкретных датчиков ==="
echo ""
echo "sensor.waveshare001_rs485_temperature_11:"
ha core states get sensor.waveshare001_rs485_temperature_11 2>/dev/null || echo "Недоступен"
echo ""
echo "sensor.waveshare001_rs485_humidity_11:"
ha core states get sensor.waveshare001_rs485_humidity_11 2>/dev/null || echo "Недоступен"
echo ""
echo "sensor.waveshare001_rs485_temperature_11:"
ha core states get sensor.waveshare001_rs485_temperature_11 2>/dev/null || echo "Недоступен"
echo ""
echo "sensor.waveshare001_rs485_humidity_11:"
ha core states get sensor.waveshare001_rs485_humidity_11 2>/dev/null || echo "Недоступен"

