# ======================================================================
# LOVELACE DASHBOARD: Брудер
# ======================================================================
# Dashboard для управления брудером перепелиной фермы
# ======================================================================

title: Брудер
views:
  - title: Брудер 2
    path: brooder-2
    icon: mdi:home-thermometer
    cards:
      # -------------------------------------------------
      # 1. УПРАВЛЕНИЕ
      # -------------------------------------------------
      - type: entities
        title: Управление
        entities:
          # Текущие показания датчиков
          - entity: sensor.waveshare001_rs485_temperature_11
            name: Температура
            icon: mdi:thermometer
          - entity: sensor.waveshare001_rs485_humidity_11
            name: Влажность
            icon: mdi:water-percent
          
          # Регулировка температуры
          - entity: input_number.min_temp
            name: Мин. температура
            icon: mdi:thermometer-low
          - entity: input_number.max_temp
            name: Макс. температура
            icon: mdi:thermometer-high
          
          # Регулировка влажности
          - entity: input_number.min_hum
            name: Мин. влажность
            icon: mdi:water-percent
          - entity: input_number.max_hum
            name: Макс. влажность
            icon: mdi:water-percent

      # -------------------------------------------------
      # 2. БЛОК "АВАРИЙНЫЙ РЕЖИМ"
      # -------------------------------------------------
      - type: custom:mushroom-title-card
        title: Аварийный режим
        subtitle: >
          {% if is_state('input_boolean.emergency_active', 'on') %}
            🚨 АВАРИЯ! Система остановлена
          {% else %}
            ✅ Система работает нормально
          {% endif %}

      - type: vertical-stack
        cards:
          - type: custom:mushroom-template-card
            primary: >
              {% if is_state('input_boolean.emergency_active', 'on') %}
                🚨 Аварийный режим АКТИВЕН
              {% else %}
                ✅ Аварийный режим неактивен
              {% endif %}
            secondary: >
              {% if is_state('input_boolean.emergency_active', 'on') %}
                Система остановлена. Требуется сброс аварии.
              {% else %}
                Система работает нормально
              {% endif %}
            icon: mdi:alert
            icon_color: >
              {% if is_state('input_boolean.emergency_active', 'on') %}
                red
              {% else %}
                green
              {% endif %}
          
          - type: custom:mushroom-template-card
            primary: Состояние брудера
            secondary: "{{ states('input_text.brooder_state') }}"
            icon: >
              {% if is_state('input_text.brooder_state', 'АВАРИЯ') %}
                mdi:alert-octagon
              {% elif is_state('input_text.brooder_state', 'Подогрев') %}
                mdi:heat-wave
              {% elif is_state('input_text.brooder_state', 'Освещение') %}
                mdi:lightbulb-on
              {% elif is_state('input_text.brooder_state', 'Проветривание') %}
                mdi:fan
              {% elif is_state('input_text.brooder_state', 'Ожидание') %}
                mdi:pause-circle
              {% else %}
                mdi:information-outline
              {% endif %}
            icon_color: >
              {% if is_state('input_text.brooder_state', 'АВАРИЯ') %}
                red
              {% elif is_state('input_text.brooder_state', 'Подогрев') %}
                orange
              {% elif is_state('input_text.brooder_state', 'Освещение') %}
                yellow
              {% elif is_state('input_text.brooder_state', 'Проветривание') %}
                cyan
              {% elif is_state('input_text.brooder_state', 'Ожидание') %}
                grey
              {% else %}
                blue
              {% endif %}
          
          - type: custom:mushroom-template-card
            primary: Причина аварии
            secondary: >
              {% if states('input_text.emergency_reason') != '' %}
                {{ states('input_text.emergency_reason') }}
              {% else %}
                Нет активной аварии
              {% endif %}
            icon: mdi:alert-octagon
            icon_color: >
              {% if states('input_text.emergency_reason') != '' %}
                red
              {% else %}
                grey
              {% endif %}
          
          - type: custom:mushroom-entity-card
            entity: input_button.reset_emergency
            name: Сброс аварии
            icon: mdi:restore-alert
            icon_color: >
              {% if is_state('input_boolean.emergency_active', 'on') %}
                orange
              {% else %}
                grey
              {% endif %}
            tap_action:
              action: button

      # -------------------------------------------------
      # 3. БЛОК "ПРОГРЕВ"
      # -------------------------------------------------
      - type: custom:mushroom-title-card
        title: Прогрев
        subtitle: Включение всех ИК ламп и всех ТЭНов

      - type: entities
        entities:
          - entity: input_boolean.ruchnoi_rezhim
            name: Ручной режим
            icon: mdi:hand-back-left
          - entity: input_button.preheat
            name: Прогрев
            icon: mdi:heat-wave
            tap_action:
              action: button
          - entity: input_button.stop_brooder
            name: Стоп
            icon: mdi:stop-circle
            tap_action:
              action: button

      # -------------------------------------------------
      # 4. УПРАВЛЕНИЕ РЕЛЕ (ВЫХОДЫ)
      # -------------------------------------------------
      - type: custom:mushroom-title-card
        title: Управление реле

      - type: entities
        entities:
          - entity: switch.waveshare001_relay_1
            name: ТЭН1
          - entity: switch.waveshare001_relay_2
            name: ТЭН2
          - entity: switch.waveshare001_relay_3
            name: Вентилятор скор.1
          - entity: switch.waveshare001_relay_4
            name: Вентилятор скор.2
          - entity: switch.waveshare001_relay_5
            name: ИК 1-2
          - entity: switch.waveshare001_relay_6
            name: ИК 3-4
          - entity: switch.waveshare001_relay_7
            name: ИК 5-6
          - entity: switch.waveshare001_relay_8
            name: Освещение

      # -------------------------------------------------
      # 5. ГРАФИКИ (история)
      # -------------------------------------------------
      - type: custom:mushroom-title-card
        title: История (24 часа)

      - type: history-graph
        entities:
          - entity: sensor.waveshare001_rs485_temperature_11
            name: Температура
          - entity: sensor.waveshare001_rs485_humidity_11
            name: Влажность
        hours_to_show: 24
        refresh_interval: 60
