# ======================================================================
# LOVELACE DASHBOARD: Брудер
# ======================================================================
# Dashboard для управления брудером перепелиной фермы
# ======================================================================

title: Брудер
views:
  - title: Брудер 2
    path: brooder-2
    icon: mdi:home-thermometer
    cards:
      # -------------------------------------------------
      # 1. ТЕМПЕРАТУРА И ВЛАЖНОСТЬ
      # -------------------------------------------------
      - type: entities
        title: Температура и влажность
        entities:
          # Используем template sensors из configuration.yaml
          - entity: sensor.brooder_temperature
            name: Температура
            icon: mdi:thermometer
          - entity: sensor.brooder_humidity
            name: Влажность
            icon: mdi:water-percent

      # -------------------------------------------------
      # 2. УПРАВЛЕНИЕ РЕЛЕ (ВЫХОДЫ)
      # -------------------------------------------------
      - type: custom:mushroom-title-card
        title: Управление реле

      - type: entities
        entities:
          - entity: switch.waveshare001_relay_1
            name: ТЭН1
          - entity: switch.waveshare001_relay_2
            name: ТЭН2
          - entity: switch.waveshare001_relay_3
            name: Вентилятор скор.1
          - entity: switch.waveshare001_relay_4
            name: Вентилятор скор.2
          - entity: switch.waveshare001_relay_5
            name: ИК 1-2
          - entity: switch.waveshare001_relay_6
            name: ИК 3-4
          - entity: switch.waveshare001_relay_7
            name: ИК 5-6
          - entity: switch.waveshare001_relay_8
            name: Освещение

      # -------------------------------------------------
      # 3. ГРАФИКИ (история)
      # -------------------------------------------------
      - type: custom:mushroom-title-card
        title: История (24 часа)

      - type: history-graph
        entities:
          - entity: sensor.brooder_temperature
            name: Температура
          - entity: sensor.brooder_humidity
            name: Влажность
        hours_to_show: 24
        refresh_interval: 60
