# ======================================================================
# DASHBOARD: Брудеры
# ======================================================================
# Обзор - показатели всех брудеров
# Отдельные views для каждого брудера
# ======================================================================

title: Брудеры
views:
  # Обзор - показатели всех брудеров
  - title: Обзор
    icon: mdi:view-dashboard
    path: overview
    badges: []
    cards:
      - type: entities
        title: Показатели брудеров
        show_header_toggle: false
        entities:
          # Брудер 2
          - entity: sensor.bruder_2_temperatura
            name: Брудер 2 - Температура
            icon: mdi:thermometer
          - entity: sensor.bruder_2_vlazhnost
            name: Брудер 2 - Влажность
            icon: mdi:water-percent

          # Для добавления нового брудера добавьте здесь:
          # - entity: sensor.brooder_3_temperature
          #   name: Брудер 3 - Температура
          #   icon: mdi:thermometer
          # - entity: sensor.brooder_3_humidity
          #   name: Брудер 3 - Влажность
          #   icon: mdi:water-percent

  # Брудер 2 - детальное управление
  - title: Брудер 2
    icon: mdi:home-thermometer-outline
    path: brooder2
    badges: []
    cards: []

  # Для добавления нового брудера раскомментируйте:
  # - title: Брудер 3
  #   icon: mdi:home-thermometer-outline
  #   path: brooder3
  #   badges: []
  #   cards: []
