# ======================================================================
# LOVELACE DASHBOARD: Брудер - Упрощенная версия
# ======================================================================
# Только контроллер и выходы подключения
# ======================================================================

title: Брудер
views:
  - title: Брудер
    icon: mdi:home-thermometer
    cards:
      # -------------------------------------------------
      # 1. ДАТЧИКИ
      # -------------------------------------------------
      - type: custom:mushroom-title-card
        title: Датчики

      - type: grid
        columns: 2
        square: false
        cards:
          - type: custom:mushroom-template-card
            primary: Температура
            secondary: "{{ states('sensor.waveshare001_rs485_temperature_10') }} °C"
            icon: mdi:thermometer
            icon_color: green

          - type: custom:mushroom-template-card
            primary: Влажность
            secondary: "{{ states('sensor.waveshare001_rs485_humidity_10')|float(0)|round(1) }} %"
            icon: mdi:water-percent
            icon_color: cyan

      # -------------------------------------------------
      # 2. УПРАВЛЕНИЕ РЕЛЕ (ВЫХОДЫ)
      # -------------------------------------------------
      - type: custom:mushroom-title-card
        title: Управление реле

      - type: entities
        entities:
          - entity: switch.waveshare001_relay_1
            name: ТЭН1
          - entity: switch.waveshare001_relay_2
            name: ТЭН2
          - entity: switch.waveshare001_relay_3
            name: Вентилятор скор.1
          - entity: switch.waveshare001_relay_4
            name: Вентилятор скор.2
          - entity: switch.waveshare001_relay_5
            name: ИК 1-2
          - entity: switch.waveshare001_relay_6
            name: ИК 3-4
          - entity: switch.waveshare001_relay_7
            name: ИК 5-6
          - entity: switch.waveshare001_relay_8
            name: Освещение

      # -------------------------------------------------
      # 3. КНОПКА ПЕРЕЗАГРУЗКИ КОНТРОЛЛЕРА
      # -------------------------------------------------
      - type: custom:mushroom-title-card
        title: Управление контроллером

      - type: custom:mushroom-buttons-card
        buttons:
          - name: Перезагрузка контроллера
            icon: mdi:restart
            icon_color: orange
            tap_action:
              action: call-service
              service: button.press
              target:
                entity_id: button.waveshare001_restart_button

      # -------------------------------------------------
      # 4. ГРАФИКИ (история)
      # -------------------------------------------------
      - type: custom:mushroom-title-card
        title: История (24 часа)

      - type: history-graph
        entities:
          - entity: sensor.waveshare001_rs485_temperature_10
            name: Температура
          - entity: sensor.waveshare001_rs485_humidity_10
            name: Влажность
        hours_to_show: 24
        refresh_interval: 60
