# ======================================================================
# LOVELACE DASHBOARD: Брудер
# ПОЛНОСТЬЮ ОЧИЩЕНО - начинаем с нуля
# ======================================================================
# Резервная копия сохранена в: backup/ui-lovelace.yaml.backup_*

title: Брудер
views:
  - title: Брудер
    icon: mdi:home-thermometer
    cards:
      - type: markdown
        content: |
          # Брудер
          
          Конфигурация очищена. Готов к настройке.
