# ======================================================================
# LOVELACE DASHBOARD: Брудер
# ======================================================================
# Dashboard для управления брудером перепелиной фермы
# ======================================================================

title: Брудер
views:
  - title: Брудер 2
    path: brooder-2
    icon: mdi:home-thermometer
    cards:
      # -------------------------------------------------
      # 1. УПРАВЛЕНИЕ
      # -------------------------------------------------
      - type: entities
        title: Управление
        entities:
          # Текущие показания датчиков
          - entity: sensor.waveshare001_rs485_temperature_11
            name: Температура
            icon: mdi:thermometer
          - entity: sensor.waveshare001_rs485_humidity_11
            name: Влажность
            icon: mdi:water-percent
          
          # Регулировка температуры
          - entity: input_number.min_temp
            name: Мин. температура
            icon: mdi:thermometer-low
          - entity: input_number.max_temp
            name: Макс. температура
            icon: mdi:thermometer-high
          
          # Регулировка влажности
          - entity: input_number.min_hum
            name: Мин. влажность
            icon: mdi:water-percent
          - entity: input_number.max_hum
            name: Макс. влажность
            icon: mdi:water-percent

      # -------------------------------------------------
      # 2. БЛОК "ПРОГРЕВ"
      # -------------------------------------------------
      - type: custom:mushroom-title-card
        title: Прогрев
        subtitle: Включение всех ИК ламп и всех ТЭНов

      - type: entities
        entities:
          - entity: input_button.preheat
            name: Прогрев
            icon: mdi:heat-wave
            tap_action:
              action: button
          - entity: input_button.stop_brooder
            name: Стоп
            icon: mdi:stop-circle
            tap_action:
              action: button

      # -------------------------------------------------
      # 3. УПРАВЛЕНИЕ РЕЛЕ (ВЫХОДЫ)
      # -------------------------------------------------
      - type: custom:mushroom-title-card
        title: Управление реле

      - type: entities
        entities:
          - entity: switch.waveshare001_relay_1
            name: ТЭН1
          - entity: switch.waveshare001_relay_2
            name: ТЭН2
          - entity: switch.waveshare001_relay_3
            name: Вентилятор скор.1
          - entity: switch.waveshare001_relay_4
            name: Вентилятор скор.2
          - entity: switch.waveshare001_relay_5
            name: ИК 1-2
          - entity: switch.waveshare001_relay_6
            name: ИК 3-4
          - entity: switch.waveshare001_relay_7
            name: ИК 5-6
          - entity: switch.waveshare001_relay_8
            name: Освещение

      # -------------------------------------------------
      # 3. ГРАФИКИ (история)
      # -------------------------------------------------
      - type: custom:mushroom-title-card
        title: История (24 часа)

      - type: history-graph
        entities:
          - entity: sensor.waveshare001_rs485_temperature_11
            name: Температура
          - entity: sensor.waveshare001_rs485_humidity_11
            name: Влажность
        hours_to_show: 24
        refresh_interval: 60
