# ----------------------------------------------------------------------
# Проект: Автоматизация перепелиной фермы (брудер) на Home Assistant
# Протокол: Modbus RTU (RS485) + WaveShare реле/датчики
# НОВАЯ ЧИСТАЯ КОНФИГУРАЦИЯ
# ----------------------------------------------------------------------

# ======================================================================
# 1. INPUT_NUMBER – параметры управления
# ======================================================================
input_number:
  min_temp:
    name: Мин Температура брудера
    min: 20
    max: 40
    initial: 30
    step: 0.5
    unit_of_measurement: °C
    icon: mdi:thermometer-low

  max_temp:
    name: Макс Температура брудера
    min: 20
    max: 40
    initial: 37
    step: 0.5
    unit_of_measurement: °C
    icon: mdi:thermometer-high

  min_hum:
    name: Мин влажность брудера
    min: 40
    max: 70
    initial: 60
    step: 1
    unit_of_measurement: '%'
    icon: mdi:water-percent

  max_hum:
    name: Макс влажность брудера
    min: 40
    max: 70
    initial: 65
    step: 1
    unit_of_measurement: '%'
    icon: mdi:water-percent

  dehum_min_temp:
    name: Мин температура для осушения
    min: 25
    max: 35
    initial: 31
    step: 0.5
    unit_of_measurement: °C
    icon: mdi:thermometer

  fan_min_on:
    name: Мин время работы вентилятора
    min: 1
    max: 10
    initial: 3
    step: 1
    unit_of_measurement: мин
    icon: mdi:timer

  temp_fan_hysteresis:
    name: Гистерезис температуры вентилятора
    min: 0.1
    max: 2.0
    initial: 0.6
    step: 0.1
    unit_of_measurement: °C
    icon: mdi:thermometer

# ======================================================================
# 2. INPUT_BUTTON – кнопки управления
# ======================================================================
input_button:
  preheat:
    name: Прогрев
    icon: mdi:heat-wave

  stop_brooder:
    name: Остановить брудер
    icon: mdi:stop-circle

# ======================================================================
# 3. INPUT_BOOLEAN – режимы работы
# ======================================================================
input_boolean:
  ruchnoi_rezhim:
    name: Ручной режим
    initial: off
    icon: mdi:hand-back-left

  avtomaticheskii_rezhim:
    name: Автоматический режим
    initial: on
    icon: mdi:robot

# ======================================================================
# 4. INPUT_TEXT – статусы
# ======================================================================
input_text:
  brooder_state:
    max: 100
    name: Состояние брудера
    initial: Ожидание
    icon: mdi:information-outline

  fan_reason:
    max: 50
    name: Причина включения вентилятора
    initial: ""
    icon: mdi:fan

# ======================================================================
# 5. INPUT_DATETIME – времена
# ======================================================================
input_datetime:
  ten1_start_time:
    name: ТЭН1 старт время
    has_date: true
    has_time: true

  fan_start_time:
    name: Вентилятор старт время
    has_date: true
    has_time: true

  fan_stop_time:
    name: Вентилятор стоп время
    has_date: true
    has_time: true

# ======================================================================
# 6. INPUT_NUMBER – служебные
# ======================================================================
input_number:
  ten1_start_temp:
    name: ТЭН1 старт температура
    min: 0
    max: 50
    initial: 0
    step: 0.1
    unit_of_measurement: °C
    icon: mdi:thermometer

# ======================================================================
# 7. NOTIFY – уведомления
# ======================================================================
notify:
  - platform: telegram
    chat_id: -4042989566
    name: brooder_notify

# ======================================================================
# 8. SCRIPT – скрипты
# ======================================================================
script:
  send_notify:
    sequence:
      - service: notify.brooder_notify
        data:
          message: >-
            Брудер 1. {{ message }} Дата {{ now().strftime('%d.%m.%Y %H:%M') }}.
            T={{ states('sensor.temperatura_brudera_2') }}°C,
            H={{ states('sensor.vlazhnost_brudera_2') }}%.

  stop_brooder:
    sequence:
      - service: input_text.set_value
        data:
          entity_id: input_text.brooder_state
          value: Ожидание
      - service: switch.turn_off
        target:
          entity_id:
            - switch.waveshare001_relay_1
            - switch.waveshare001_relay_2
            - switch.waveshare001_relay_3
            - switch.waveshare001_relay_4
            - switch.waveshare001_relay_5
            - switch.waveshare001_relay_6
            - switch.waveshare001_relay_7
            - switch.waveshare001_relay_8
      - service: input_text.set_value
        data:
          entity_id: input_text.fan_reason
          value: ""
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.avtomaticheskii_rezhim
      - service: script.send_notify
        data:
          message: "Брудер остановлен. Все устройства отключены."

# ======================================================================
# 9. AUTOMATION – автоматизации
# ======================================================================
automation:

  # Ручной режим → отключение автоматического режима
  - alias: "[Брудер] Ручной режим → отключение автоматического режима"
    trigger:
      - platform: state
        entity_id: input_boolean.ruchnoi_rezhim
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.avtomaticheskii_rezhim
        state: "on"
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.avtomaticheskii_rezhim
      - service: script.send_notify
        data:
          message: "Ручной режим включен. Автоматический режим отключен."

  # Автоматический режим → отключение ручного режима
  - alias: "[Брудер] Автоматический режим → отключение ручного режима"
    trigger:
      - platform: state
        entity_id: input_boolean.avtomaticheskii_rezhim
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.ruchnoi_rezhim
        state: "on"
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.ruchnoi_rezhim
      - service: script.send_notify
        data:
          message: "Автоматический режим включен. Ручной режим отключен."

  # Кнопка Стоп
  - alias: "[Брудер] Остановка – кнопка Стоп"
    trigger:
      - platform: state
        entity_id: input_button.stop_brooder
    action:
      - service: script.stop_brooder
